name: AncientCitiesControl
version: ${project.version}
main: cz.stepes.ancientcitiescontrol.AncientCitiesControl
api-version: 1.19
load: STARTUP
authors:
  - Stepes
  - Atilt
description: Ability to control generation rates on Ancient Cities

commands:
  ancientcities:
